### ISSUE TITLE
Detailed performance analysis of RESCAL

### ISSUE THREAD

**Issue by fkleedorfer** [researchstudio-sat/wonpreprocessing#9]
Hypothesis: 
Overly general postings are matched with many postings by humans but confuse RESCAL. Eliminating them might improve quality. 
Approach: 
Correlate node-degree and number of categories with matcher performance (precision/recall/f0.5-measure). If there is a correlation, remove postings with too many connections or categories. 

Same may apply inversely to postings with too few connections

**Comment by heikofriedrich** [comment]
- " remove postings with too many connections or categories. " => didnt improve the predictions => implemented as "nohubneeds_eval()"

Stats or Performance for individual categories can be seen approximately in gephi but is not explicitly and excactly computed, this would require extra implementation effort.
But if this data is needed to find out the reasons for bad performance of RESCAL this can also to some degree be done in gephi. See my comments that go in this direction in "R:\02 projekte aktuell\1305-USS WON-COIN\Projektlogbuch-Matching_1.0_141216_hf"

**Comment by heikofriedrich** [comment]
i have exported the graph data to excel, there serveral performance and graph stats can be seen per category, see file R:\02 projekte aktuell\1305-USS WON-COIN\03 work\Scalability and Matching\matching-tensorbased\Techreports\graph_details_rescal_category_2010113
